### ISSUE TITLE
Check and implement proper timezone manipulations

### ISSUE THREAD

**Issue by weakcamel** [nokia/git-changelog-generator#4]
See FIXME items

https://github.com/nokia/git-changelog-generator/blob/b08973433ab6971301fdf713df1a578ea75a459f/gcg/entrypoint.py#L208

https://github.com/nokia/git-changelog-generator/blob/b08973433ab6971301fdf713df1a578ea75a459f/gcg/entrypoint.py#L224

**Comment by neechbear** [comment]
https://gitpython.readthedocs.io/en/stable/reference.html#module-git.objects.commit

From the looks of the docs, it's stored as seconds since UTC epoch, so maybe you can just bung the value through [pytz](http://pytz.sourceforge.net/) to transform it to alternate timezones?

Wouldn't we just want to output as the local timezone though?

**Comment by weakcamel** [comment]
Output at local timezone - yes, absolutely.  The input (commits, tags) may be coming from any timezone and I have this sinking feeling that I'm handling it wrong, especially for DEB :)

**Comment by weakcamel** [comment]
https://julien.danjou.info/python-and-timezones/

I'll have a look also whether pytz helps here or can this be done purely with standard library; the data we get for timezone is "UTC offset in seconds", not actual timezone.

**Comment by felfert** [comment]
I have looked at several rpm spec files from redhat. **None** of them shows timezones in the changelog.
Not even time, only dates. So: At least for rpm format, this is not needed.
I also looked at changelog on an Ubuntu 18.04 machine and with that one, time zonees are shown as
tz-offsets (no names needed). Should be pretty easy to implement.

**Comment by weakcamel** [comment]
Thanks for checking. For RPMs it's less of an issue yet I was thinking about the case when with tagging and actual build happening in different timezones, different zone might mean a different day. RPM changelog should IMO show local date then (which may in rare cases be different than the tagger's date).
